from graphframes import GraphFrame
from pyspark import SparkContext
from pyspark.sql import SQLContext

class Graphs:
    _sql: SQLContext
    _sc: SparkContext
    def __init__(self, sqlContext: SQLContext) -> None: ...
    def friends(self) -> GraphFrame: ...
    def gridIsingModel(
        self, n: int, vStd: float = ..., eStd: float = ...
    ) -> GraphFrame: ...
